name = "Ritzy"
license = "MIT"
licenselink = "https://github.com/ddritzenhoff/ritzy/blob/master/LICENSE"
description = "A simple Hugo theme focused on blogging and information density."
tags = ["blog", "density"]
features = []
min_version = "0.41.0"

[author]
  name = "Dominik Ritzenhoff"
  homepage = "dominikritzenhoff.com"
